//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace libQB.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libQB.Properties.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The application is already running. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_DualBoot {
            get {
                return ResourceManager.GetString("Alert_DualBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Not Found! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alert_FileNotFound {
            get {
                return ResourceManager.GetString("Alert_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Clear {
            get {
                return ResourceManager.GetString("Button_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_No {
            get {
                return ResourceManager.GetString("Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Yes {
            get {
                return ResourceManager.GetString("Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_OpenFile {
            get {
                return ResourceManager.GetString("Common_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SaveFile {
            get {
                return ResourceManager.GetString("Common_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_SelectFolder {
            get {
                return ResourceManager.GetString("Common_SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to finish? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm_ApplicationClose {
            get {
                return ResourceManager.GetString("Confirm_ApplicationClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to finish with the changes? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm_ApplicationCloseWithTheChanges {
            get {
                return ResourceManager.GetString("Confirm_ApplicationCloseWithTheChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to clear it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm_CommandClear {
            get {
                return ResourceManager.GetString("Confirm_CommandClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to delete it? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm_CommandDelete {
            get {
                return ResourceManager.GetString("Confirm_CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Current Contents Are Discarded. Do You Still Want To Execute? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm_NewFile {
            get {
                return ResourceManager.GetString("Confirm_NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please correct the error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Confirm_SaveHasError {
            get {
                return ResourceManager.GetString("Confirm_SaveHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Command_Clear {
            get {
                return ResourceManager.GetString("Title_Command_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Command_Delete {
            get {
                return ResourceManager.GetString("Title_Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Dialog_Alert {
            get {
                return ResourceManager.GetString("Title_Dialog_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Dialog_Confirm {
            get {
                return ResourceManager.GetString("Title_Dialog_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Dialog_Error {
            get {
                return ResourceManager.GetString("Title_Dialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Dialog_Infomation {
            get {
                return ResourceManager.GetString("Title_Dialog_Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Dialog_Warning {
            get {
                return ResourceManager.GetString("Title_Dialog_Warning", resourceCulture);
            }
        }
    }
}
