//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace libQB.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("libQB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Clear Selected {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Command_Clear {
            get {
                return ResourceManager.GetString("Message_Command_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete Selected {0} &apos;{1}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_Command_Delete {
            get {
                return ResourceManager.GetString("Message_Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Complete! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ProcessComplete {
            get {
                return ResourceManager.GetString("Message_ProcessComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid clipboard content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasteError {
            get {
                return ResourceManager.GetString("PasteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Accent Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_AccentColor {
            get {
                return ResourceManager.GetString("Setting_AccentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Language {
            get {
                return ResourceManager.GetString("Setting_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_PageTitle {
            get {
                return ResourceManager.GetString("Setting_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Up Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_SatartUpPage {
            get {
                return ResourceManager.GetString("Setting_SatartUpPage", resourceCulture);
            }
        }
    }
}
